---
title: "ANOVA with one explanatory variable"
runtime: shiny
output: html_document
---

```{r include=FALSE}
library(NHANES)
library(ggformula)
library(dplyr)
library(StatPREPshiny)
knitr::opts_chunk$set(echo = TRUE)
explanatory_vars <- c("Gender", "HomeOwn", "SmokeNow", "SexEver", "PregnantNow", "Depressed", "Work", "PhysActive" )
response_vars <- c("Age", "Poverty", "Pulse", "BMI", "TotChol", "BPSys1", "UrineVol1", "Weight", "Height", "DaysMentHlthBad", "LittleInterest", "Age1stBaby", "PhysActiveDays", "SexNumPartnLife")
```


```{r echo = FALSE}
A <- selectInput("response", "Response variable",
                 choices = response_vars, width = "130px")
B <- selectInput("explan", "Explanatory variable",                
                 choices = explanatory_vars, width = "130px")
SAMPN <- selectInput("samp_n", "Sample size:", choices = c(20, 50, 100, 200, 500, 1000),
                     selected = "50", width = "100px")
SHOWSD <- checkboxInput("show_sd", "Show std. deviations", value = TRUE, width = "130px")
STATS <- verbatimTextOutput("r-and-p")
F_REPORT <- verbatimTextOutput("stats")
SEED <- actionButton("seed", "New Sample")
PLOT <- plotOutput("plot1", width = "500px")
DISPLAY <- tabsetPanel(tabPanel("Graphics", PLOT), tabPanel("F-test", F_REPORT))
```


```{r echo = FALSE}
# For the package??
annotate_factor  <- function(x, before = NULL, after = NULL) {
  x <- as.factor(x)

  factor(x, levels = c(before, levels(x), after))
}
```


```{r context = "server", echo = FALSE}
get_data_frame <- function() {NHANES}
get_sample   <- reactive({
  set.seed(input$seed)
  df <- get_data_frame()
  resp   <- df[[response_name()]]
  explan <- factor(df[[explan_name()]])
  explan <- annotate_factor(explan, after = c("  ", "model_vals", "raw_vals"))
  
  res <- data.frame(explan, resp, color = explan)
  names(res) <- c(explan_name(), response_name(), "color")
  
  res %>% na.omit() %>% sample_n(size = samp_n())

})
observe({updateActionButton(session, "seed", label = paste("New sample with n =", req(samp_n())))})
response_name <- reactive({req(input$response)})
explan_name   <- reactive({req(input$explan)})
plot_formula  <- reactive({as.formula(paste(response_name(), "~", explan_name()))})
color_formula <- reactive({as.formula(paste("~", explan_name()))})
model_val_formula <- reactive({
  as.formula(paste(response_name(), "+", response_name(), "~", explan_name()))
})
sd_formula    <- reactive({
  as.formula(paste("middle + top ~ ", explan_name()))
})
explan_levels <- reactive({
  as.character(unique(get_data_frame()[[explan_name()]]))
})
samp_n       <- reactive({as.numeric(req(input$samp_n))})

color_scale <- reactive({
  StatPREP_color_scale(explan_levels())
})
fit_mod <- reactive({
  lm(plot_formula(), data = get_sample())
})
mod_stats <- reactive({
  res <- with(summary(fit_mod()), as.list(c(c(rsq = r.squared), fstatistic)))
  res$pvalue = 1 - pf(res$value, res$numdf, res$dendf)
  res$n = res$numdf + res$dendf + 1
  res$numdf <- as.integer(res$numdf)
  res$dendf <- as.integer(res$dendf)
  res
})
annotated_model_values <- reactive({
  mod <- fit_mod()
  data <- get_sample()
  explan <- data[[explan_name()]]
  val <- predict(mod, newdata = data[explan_name()])
  raw <- data[[response_name()]]
  values <- c(raw, val)
  category <- factor(c(rep("raw_vals", nrow(data)), 
                       rep("model_vals", nrow(data))), 
                     levels = levels(explan))
  res <- data.frame(explan, val, orig_explan = explan)
  res2 <- data.frame(explan = category, val = values, 
                     orig_explan = factor(rep(explan, 2), levels = levels(explan)))
  res <- rbind(res, res2)
  names(res) <- c(explan_name(), response_name(), "orig_explan")
  res$color <- res[[explan_name()]]
  res
})

Stats <- reactive({
  df_stats(plot_formula(), data = annotated_model_values(),
           middle = mean, s = sd, long_names = FALSE ) %>% 
  na.omit() %>%
  mutate(top = middle + s )
})
graphics <- reactive({
  P <- gf_errorbar(model_val_formula(), 
              data = unique(annotated_model_values()), 
              color = ~ color) %>%
       gf_jitter(plot_formula(), data = get_sample(), color = color_formula(), height = 0, width = 0.1) 
  if (input$show_sd) 
    P <- P %>% gf_linerange(sd_formula(), data = Stats(), color = "black", size = 5, alpha = 0.5)
  
  P %>% 
    gf_refine(
      scale_color_manual(
      values = StatPREP_color_scale(explan_levels(), 
                                    annot_levels = c("model_vals", "raw_vals"), 
                                    annot_colors  =c("tomato1", "tomato2"))
      )) %>% gf_theme(legend.position = "none")
})
r_and_p_string <- reactive({
  tmp <- mod_stats()
  tmp$rsq <- signif(100*tmp$rsq, 3)
  
  sprintf("R²  = %g%%\n1-R²=%g%%\n%s",
          tmp$rsq, 100-tmp$rsq, nice_p(tmp$pvalue))
})
output$plot1 <- renderPlot({graphics()})
output$`r-and-p` <- renderText({r_and_p_string()})
output$stats <- renderText({
  tmp <- mod_stats()
  tmp$rsq <- signif(100*tmp$rsq, 3)
  third <- sprintf("F = R²/df_mod ÷ (1-R²)/df_res\n  = (%g/%d) ÷ (%g/%d) = %g\n",
            tmp$rsq, tmp$numdf, 100-tmp$rsq, tmp$dendf, signif(tmp$value,3))
  
  label = paste0(
    sprintf("R²=%g%%     1-R²= %g%%\n", tmp$rsq, 100-tmp$rsq),
    sprintf("Deg. Freedom: Total %d, model %d, resids %d\n", tmp$n, tmp$numdf, tmp$dendf),
    third,
    sprintf("F=%g with %d and %d df ➼ %s", signif(tmp$value,3), 
            tmp$numdf, tmp$dendf, nice_p(tmp$pvalue)),
    collapse = "")
  
  label
})
```
  
<table><tr><td class="control">`r SAMPN` `r A` `r B` `r SHOWSD` `r STATS` `r SEED` </td><td class="plot">`r DISPLAY`</td></tr></table>

<style type="text/css">
td.control {
  border:1px solid gray;
  border-radius:10px;
  padding: 5px;
  vertical-align: top;
}
td.plot {
  border:1px solid gray;
  padding: 5px;
  border-radius:10px;
  color: white;
}

</style>


