---
title: "Two-sample t test"
runtime: shiny
output: html_document
---


```{r include = FALSE}
library(mosaic)
library(mosaicCore)
library(mosaicData)
library(ggformula)
library(dplyr)
library(NHANES)
library(markdown)
library(StatPREPshiny)
explanatory_vars <- c("Gender", "HomeOwn", "SmokeNow", "SexEver", "PregnantNow", "Depressed", "Work", "PhysActive" )
response_vars <- c("Age", "Poverty", "Pulse", "BMI", "TotChol", "BPSys1", "UrineVol1", "Weight", "Height", "DaysMentHlthBad", "LittleInterest", "Age1stBaby", "PhysActiveDays", "SexNumPartnLife")
NHANES <- NHANES %>% filter(Age >= 18)
```

```{r BOGUS, eval = FALSE, echo = FALSE}
input <- list(response = "BMI", explan = "SmokeNow", samp_n = "200", seed = "1", equal_var = TRUE,
              layers = c("T", "Conf. interval"), show_90_level = TRUE, center_on = "bottom")

```


```{r echo = FALSE}
A <- selectInput("response", "Response variable",
                 choices = response_vars, width = "150px")
B <- selectInput("explan", "Explanatory variable",
                 choices = explanatory_vars, width = "150px")
N <- selectInput("samp_n", "Sample size:", choices = c(5, 10, 20, 50, 100, 500, 1000),
                 selected = "50", width = "100px")
C <- checkboxGroupInput("layers", "Inferential statistics",
                        c("T", "Conf. interval"), width = "150px", inline = TRUE)
NINETY <- checkboxInput("show_90_level", "CI at 90%", FALSE, width = "150px")
SEED <- actionButton("seed", "New sample",  width = "150px")
EV <- checkboxInput("equal_var", "Assume equal variance", FALSE, width = "150px")
CENTER <- radioButtons("center_on", "T location:", choices = c("Left", "Right"), inline = TRUE, width = "150px")
PV <- htmlOutput("pvalue")
P <- plotOutput("plot1", width = "500px",
                brush = brushOpts("horiz_line", direction = "x", fill = NA))
EXPLAIN <- htmlOutput("explain")
CODEBOOK <- verbatimTextOutput("codebook")
DISPLAY <- tabsetPanel(tabPanel("Main graphic", P), 
                       # tabPanel("Explain annotations", EXPLAIN),
                       tabPanel("Codebook", CODEBOOK))
keepers <- list(
  PregnantNow = c("Yes", "No"),
  SmokeNow = c("Yes", "No"),
  HomeOwn = c("Own", "Rent"), 
  Depressed = c("None", "Most"),
  Work = c("Working", "NotWorking"),
  PhysActive = c("Yes", "No"),
  SexEver = c("Yes", "No"),
  Gender = c("male", "female"),
  LittleInterest = c("None", "AlmostAll")
)


```

<table><tr><td class="control">`r A` `r B` `r N` `r C` `r PV` `r SEED` `r EV` `r CENTER` `r NINETY` <a href="http://StatPREP.org">Explain annotations</a> </td><td class="plot">`r DISPLAY`</td></tr></table>

<style type="text/css">
td.control {
  border:5px solid gray;
  border-radius:10px;
  padding: 5px;
  vertical-align: top;
}
td.plot {
  border:5px solid gray;
  padding: 5px;
  border-radius:10px;
  color: white;
}
</style>




```{r context = "server", echo = FALSE}
the_width <- reactive({0.1})

the_formula <- reactive({
  as.formula(paste(req(input$response), "~", req(input$explan)))
})
get_data <- reactive({
  res <- NHANES[, all.vars(the_formula())] %>% na.omit()
  res[res[[input$explan]] %in% keepers[[input$explan]], ]
})
samp_n <- reactive( {
  as.numeric(input$samp_n)
})
get_samp <- reactive( {
  set.seed(as.numeric(input$seed))
  get_data() %>% sample_n(size = samp_n())
})


color_formula <- reactive( {
  as.formula(paste("~", input$explan))
})


stats_interval <- reactive( {
  this_level <- ifelse(input$show_90_level, .9, .95)
  df_stats(the_formula(), data = get_samp(), 
           mn = mean, ci = ci.mean(level = !!this_level), long_names = FALSE) %>% 
    mutate(xpos = c(1.25, 1.75))
})

output$pvalue <- renderText({
  if ("T" %in% input$layers ) nice_p(t_interval()$p.value)
  else ""})

t_interval <- reactive( {
  tmp <- stats::t.test(the_formula(), data = get_samp(), var.equal = input$equal_var)
  
  if (input$center_on == "Left") { 
    res <- tmp$estimate[2] + tmp$conf.int 
    #res <- res + abs(diff(tmp$estimate))
  } else {
    res <- tmp$estimate[1] - tmp$conf.int 
    #res <- res - abs(diff(tmp$estimate))
  }
  res <- as.list(res)
  names(res) <- c("low", "high")
  res$midpoint <- 1.5
  res$p.value <- tmp$p.value
  as.data.frame(res)
})
graphics <- reactive( {
  set.seed(101)
  width_val <- 0.1

  P <- gf_jitter(the_formula(), data = get_samp(), 
                 color = color_formula(),
                 alpha = point_alpha(samp_n()),
                 width = 0.1,
                 height = 0,
                 show.legend = FALSE)
  
  P <- P %>% gf_errorbar(mn + mn ~ xpos,
                        data = stats_interval(), color = color_formula(),
                        show.legend = FALSE, 
                        width = 3 * 0.1, size=2, alpha = .5)
  if ("Conf. interval" %in% input$layers) {
    P <- P %>%
      gf_errorbar(as.formula(paste("ci_lower + ci_upper ~ ", input$explan)),
                  data = stats_interval(),
                  color = color_formula(), 
                  width = 1.3 * 0.1, size = 2, show.legend = FALSE)
  }
  
  if ("T" %in% input$layers) {
    tstats <- t_interval()
    P <- P %>% 
      gf_errorbar(low + high ~ midpoint, data = tstats, 
                  width = 1, show.legend = FALSE) 
  }
  set.seed(NULL)
  P
})

output$plot1 <- renderPlot(graphics())
output$codebook <- renderText({
    LA_var_help("NHANES", input$response, input$explan, line_length = 40L)
})
output$explain <- renderText({HTML(includeMarkdown("t-statistic-explain.md"))})
```

