---
title: "Why use density?"
runtime: shiny
output: html_document
---

```{r include=FALSE}
library(NHANES)
library(ggformula)
library(StatPREPshiny)
library(dplyr)
knitr::opts_chunk$set(echo = TRUE)
NHANES <- NHANES %>% mutate(PregnantNow = ifelse(is.na(PregnantNow), "No", as.character(PregnantNow)))
```


```{r echo = FALSE}
A <- selectInput("response", "Response variable",
                 choices = c("Weight", "Height", "Poverty", "Pulse", 
                             "BMI", "TotChol", "BPSys1", "UrineVol1", 
                             "Testosterone", "Age", "Pulse", "UrineVol1"), 
                 width = "130px")
B <- selectInput("explan", "Explanatory variable",                
                 choices = c("Diabetes", "Gender", "HomeOwn", "SmokeNow", 
                             "SexEver", "PregnantNow", "Depressed", "Work",
                             "PhysActive", "AgeDecade" ), 
                 width = "130px")
C <- radioButtons("display", "Type of display:",
                        c("histogram", "density"), width = "130px")
P <- plotOutput("plot1", width = "500px")
Pviolin <- plotOutput("pviolin", width = "500px")
CODEBOOK <- verbatimTextOutput("codebook")
DISPLAY <- tabsetPanel(
  tabPanel("Count/density axis", P),
  tabPanel("Response vs Explanatory", Pviolin),
  tabPanel("Codebook", CODEBOOK)
)
```




```{r echo = FALSE, context = "server"}
the_formula <- reactive(as.formula(paste("~", input$response, "|", input$explan)))
the_violin_formula <- reactive({
  as.formula(paste(input$response, "~", input$explan))
})




graphics <- reactive({
  if (input$display == "histogram")
    gf_histogram(the_formula(), data = NHANES)
  else gf_density(the_formula(), data = NHANES)
})


output$plot1 <- renderPlot({graphics()})
output$pviolin <- renderPlot({
  gf_jitter(the_violin_formula(), data = NHANES, 
            alpha = point_alpha(nrow(NHANES)),
            width = 0.2) %>%
  gf_violin(the_violin_formula(), data = NHANES, alpha = 0.5,
            fill = "green", color = "green")
})
output$codebook <- renderText({
    LA_var_help("NHANES", input$response, input$explan, line_length = 40L)
})
```

<table><tr><td class="control">`r A` `r B` `r C`</td><td class="plot">`r DISPLAY`</td></tr></table>



<style type="text/css">
td.control {
  border:1px solid gray;
  border-radius:10px;
  padding: 5px;
  vertical-align: top;
}
td.plot {
  border:1px solid gray;
  padding: 5px;
  border-radius:10px;
  color: white;
}

</style>


