---
title: "Smoothing"
runtime: shiny
output: html_document
---


```{r include = FALSE}
library(LittleApps)
library(mosaicModel)
library(ggformula)
library(dplyr)
library(NHANES)
library(splines)

covariates <- c("Gender", "HomeOwn", "SmokeNow", "PregnantNow", "Depressed", "Work", "PhysActive" )
response_vars <- c("Age", "Poverty", "Pulse", "BMI", "TotChol", "BPSys1", "UrineVol1", "Weight", "Height", "DaysMentHlthBad", "LittleInterest", "Age1stBaby", "PhysActiveDays", "SexNumPartnLife")
```


```{r echo = FALSE}
RESPONSE <- selectInput("response", "Response variable",
                 choices = response_vars, selected = "Height", width = "150px")
EXPLAN <- selectInput("explan", "Explanatory variable",
                 choices = response_vars, selected = "Age", width = "150px")
COVAR <- selectInput("covar", "Covariate", 
                     choices = c("NONE", as.list(covariates)), 
                     selected = "Gender", width = "150px")
SAMP_N <- selectInput("samp_n", "Sample size:", choices = c(5, 10, 20, 50, 100, 500, 1000),
                 selected = "50", width = "100px")
INTERACTION <- checkboxInput("interaction", "Include interaction", TRUE, width = "150px")
SMOOTHING <- selectInput("smoothing", "Smoothing/Curviness", 
                         choices = 1:6, width = "150px")
INTERVALS <- selectInput("interval_type", "Interval type",
                         choices = c("none", "confidence", "prediction"),
                         width = "150px")
NEW_TRIAL <- actionButton("seed", "Take new sample")
SHOW_MOD_VALUES <- checkboxInput("show_mod_values", "show model values", width = "150px")
TRACE_H <- checkboxInput("trace_horizontally", "trace horizontally", width = "150px")
TRACE_V <- checkboxInput("show_resids", "trace vertically", width = "150px")
PLOT <- plotOutput("plot", width = "500px",
                brush = brushOpts("horiz_line", direction = "x", fill = NA))
ANOVA <- verbatimTextOutput("anova_report")
REGRESSION <- verbatimTextOutput("regression_report")
CODEBOOK <- verbatimTextOutput("codebook")
DISPLAY <- tabsetPanel(tabPanel("Graphics", PLOT), 
                       tabPanel("ANOVA report", ANOVA), 
                       tabPanel("Regression report", REGRESSION),
                       tabPanel("Codebook", CODEBOOK))

```

<!-- display the input controls and output spaces -->
<table><tr>
  <td class="control">`r RESPONSE` `r EXPLAN` `r COVAR` `r INTERACTION` `r SMOOTHING` `r SAMP_N`  `r NEW_TRIAL` <hr> `r SHOW_MOD_VALUES` `r TRACE_H` `r TRACE_V` </td>
  <td class="plot">`r DISPLAY`</td>
</tr></table>

```{r context = "server", echo = FALSE}
# whether to run in shiny-reactive or mock-reactive mode
#reactive <- react_calc # comment this out for shiny mode

# Leave the ! TRUE ==, that's a feature of all.equal()
is_shiny <- ! TRUE == all.equal(reactive, LittleApps::react_calc)
if (! is_shiny) {
  output <- list
  renderPlot <- renderText <- renderTable <- I
  input <- list(response = "Height",
              explan_var = "Age",  covar = "Gender",
              samp_n = "40", seed = "1",
              interaction = TRUE, smoothing = "1", interval_type = "confidence",
              show_mod_values = TRUE, show_resids = TRUE, show_horizontally = TRUE)
  }


model_formula <- reactive({
  base_str <- paste(input$response, "~ ns(", input$explan, ", ", input$smoothing, ")")
  if ("NONE" != input$covar)
    base_str <- paste(base_str, is_interaction(), input$covar)
  
  as.formula(base_str)
})
frame_formula <- reactive({
  as.formula(paste(input$response, "~", input$explan))
})
color_formula <- reactive({
  if (input$covar == "NONE") "black"
  else as.formula(paste("~", input$covar))
})
is_interaction <- reactive({
  ifelse(input$interaction, "*", "+")
})
fit_model <- reactive({
  lm(model_formula(), data = get_sample())
})
ebar_width <- reactive({
   x_range <- range(get_data()[[input$explan]], na.rm = TRUE)
   diff(x_range) / 15
})

get_data  <- reactive({
  NHANES
})
samp_size <- reactive({
  as.numeric(input$samp_n)
})
get_sample<- reactive({
  set.seed(input$seed)
  vars <- c(input$response, input$explan)
  if("NONE" != input$covar) vars <- c(vars, input$covar)
  res <- get_data()[vars] %>% na.omit() %>% sample_n(size = samp_size())
  if (input$covar != "NONE") 
    res[["point_color"]] <- res[[input$covar]] # for plotting
  else res[["point_color"]] <- "black"
  
  res
})
scatter_plot <- reactive({
  gf_point(frame_formula(), data = get_sample(), color = color_formula())
})
regression_report <- reactive({paste(capture.output(summary(fit_model()))[-(1:8)], collapse = "\n")})
anova_report <- reactive({paste(capture.output(anova(fit_model())), collapse = "\n")})

graphics <- reactive({
  # Get the model functions for plotting
  mfundata <- mod_eval(fit_model(), nlevels = Inf, interval = input$interval_type)
  
  mod_vals <- mod_eval(fit_model(), data = get_sample())
  x_range <- range(mfundata[[input$explan]])
  x_max <- x_range[2] + 0.25 * diff(x_range)
  x_mod_vals <- x_range[2] + 0.1 * diff(x_range)
  x_raw_vals <- x_range[2] + 0.2 * diff(x_range)
  mod_vals$x_mod_vals <- x_mod_vals
  mod_vals$x_raw_vals <- x_raw_vals
  mod_vals$raw <- get_sample()[[input$response]]
  ebar_width <- diff(x_range)/15
  std_bars <- data.frame(base = rep(mean(mod_vals$raw, na.rm = TRUE), 2),
                         x = c(x_mod_vals, x_raw_vals))
  std_bars$top <- std_bars$base + c(sd(mod_vals$model_output, na.rm = TRUE),
                                    sd(mod_vals$raw, na.rm = TRUE))
  
  P <- scatter_plot() %>% 
    gf_line(as.formula(paste("model_output ~ ", input$explan)), 
            data = mfundata, color = color_formula()) %>%
    gf_theme(legend.position = "top") 
    
  P <- P %>% gf_errorbar(model_output + model_output ~ x_mod_vals, data = mod_vals, 
                 width = ebar_width(), color = "red") %>%
             gf_errorbar(raw + raw ~ x_raw_vals, data = mod_vals, 
                 width = ebar_width(), color = "red")

  # # confidence bands
  # # gf_ribbon() not working for some unknown reason.
  # 
  # P <- P %>% gf_ribbon(data = mfundata, 
  #               as.formula(paste("lower + upper ~ ", input$explan)), 
  #               alpha = 0.2, fill = color_formula(), color = NA)
  # Make sure to define INTERVALS above and to place it in user interface

  
  if (input$show_mod_values)
    P <- P %>% gf_point(as.formula(paste("model_output ~", input$explan)),
                        data = mod_vals, color = color_formula(), shape = 2)

  if (input$trace_horizontally)
    P <- P %>% gf_segment(
      as.formula(paste("model_output + model_output ~ ", input$explan, "+ x_mod_vals")),
      data = mod_vals,
      color = "black", size = 0.1)

  if (input$show_resids)
    P <- P %>% gf_segment(as.formula(paste("model_output + raw ~ ",
                                           input$explan, "+", input$explan)),
                          data = mod_vals,
                          color = "black", size = 0.1)
  
  P <- P %>% gf_segment(base + top ~ x + x, data = std_bars, 
                          size = ebar_width()/2, color = "black", alpha = 0.5)
    
  P
})

```

```{r eval = ! is_shiny, echo = FALSE}
graphics()
```
```{r context = "server", eval = is_shiny,  echo = FALSE}
output$plot <- renderPlot({graphics()}) 
output$anova_report <- renderText({anova_report()})
output$regression_report <- renderText({regression_report()})
output$codebook <- renderText({
  LA_var_help("NHANES", input$response, input$explan, input$covar, 
              line_length = 40L)
})
```

<style type="text/css">
td.control {
  border:5px solid gray;
  border-radius:10px;
  padding: 5px;
  vertical-align: top;
}
td.plot {
  border:5px solid gray;
  padding: 5px;
  border-radius:10px;
  color: white;
}

</style>

