---
title: "Proportions"
runtime: shiny
output: html_document
---


```{r include = FALSE}
library(StatPREPshiny)
library(mosaicModel)
library(ggformula)
library(dplyr)
library(NHANES)
library(splines)


response_vars <- c("High BP", "Own Home", "Above Poverty Level", "Pregnant", "Depressed")

categorical_vars <- c("HomeOwn", "SmokeNow", "PregnantNow", "Depressed", "Work", "PhysActive" )
  # Gender is added at the selectInput stage, so it will be second.
quantitative_vars <- c("Age", "Poverty", "Pulse", "BMI", "TotChol", 
                       "BPSys1", "UrineVol1", "Weight", "Height", "DaysMentHlthBad", 
                       "LittleInterest", "Age1stBaby", "PhysActiveDays", "SexNumPartnLife")
UPPER_GRAPH_LIMIT <- 1.1
LOWER_GRAPH_LIMIT <- -0.1
```



```{r echo = FALSE}
RESPONSE <- selectInput("response", "Response variable",
                 choices = response_vars, selected = response_vars[1], width = "150px")
EXPLAN <- selectInput("explan", "Explanatory variable",
                 choices = c("none", "Gender", sort(c(categorical_vars,quantitative_vars))), 
                 selected = "Gender", width = "150px")
SAMP_N <- selectInput("samp_n", "Sample size:", choices = c(5, 10, 20, 50, 100, 500, 1000),
                 selected = "50", width = "100px")
DISCRETIZE <- selectInput("quantiles", "Break into quantiles", 
                          choices = c(0, 2, 3, 4, 5, 7, 9),
                          width = "150px")

NEW_TRIAL <- actionButton("seed", "Take new sample")
SHOW_CI <- checkboxInput("show_ci", "Show Conf. Intervals", FALSE)
HOLD <- checkboxInput("hold_trials", "Retain trials", FALSE)
MODE <- radioButtons("samp_mode", label = NULL, choices = c("sample", "resample"))
LOGISTIC <- checkboxInput("logistic", "Use logistic regression", FALSE)
SMOOTH <- selectInput("smooth", "Smoothing/Curviness", choices = 1:6, width = "150px")

PLOT <- plotOutput("plot", width = "500px",
                brush = brushOpts("horiz_line", direction = "x", fill = NA))
TABLE <- verbatimTextOutput("cross-tab")
CODEBOOK <- verbatimTextOutput("codebook")
DISPLAY <- tabsetPanel(tabPanel("Graphics", PLOT), 
                       tabPanel("Tabulate", TABLE),
                       tabPanel("Codebook", CODEBOOK))
```

<!-- display the input controls and output spaces -->
<table><tr>
  <td class="control">`r RESPONSE` `r EXPLAN` `r SAMP_N` `r DISCRETIZE` <hr> Inference `r SHOW_CI`  `r HOLD` `r NEW_TRIAL` <hr> Modeling `r MODE` `r LOGISTIC` `r SMOOTH` </td>
  <td class="plot">`r DISPLAY` </td>
</tr></table>

```{r echo = FALSE}
get_model_vals <- function(data, logistic, form) { # Not reactive
  fit_fun <- 
    if (logistic) function(data, form) {glm(form, data = data, family = binomial)}
    else function(data, form) {lm(form, data = data)}
  mod <- fit_fun(data, form)
  if (form == (binary ~ 1)) {
    # work around for bug in mosaicModel (issue 11 in mosaicModel) 
    outvals <- data.frame(explan = "All Cases")
    if (logistic) {
      from_pred <- predict(mod, newdata = data[1,], se.fit = TRUE, type = "link")
      logistic_fun <- function(x) exp(x) / (1 + exp(x))
      outvals$model_output <- logistic_fun(from_pred$fit)
      outvals$upper <- logistic_fun(from_pred$fit + 1.96 * from_pred$se.fit)
      outvals$lower <- logistic_fun(from_pred$fit - 1.96 * from_pred$se.fit)
    } else {
      from_pred <- predict(mod, newdata = data[1,], interval = "confidence")
      outvals$model_output <- as.numeric(from_pred[1,1])
      outvals$lower <- from_pred[1,2]
      outvals$upper <- from_pred[1,3]
    } 
    if (any(table(current_sample$binary) == 0)) {
      # One class is empty, do conf intervals another way
      
      # ADD THIS IN
    }
    res <- outvals
  } else {
    res <- mod_eval(mod, nlevels = Inf, interval = "confidence")
  }
  
  res$upper <- ifelse(res$upper > UPPER_GRAPH_LIMIT, UPPER_GRAPH_LIMIT, res$upper)
  res$lower <- ifelse(res$lower < LOWER_GRAPH_LIMIT, LOWER_GRAPH_LIMIT, res$lower)
  
  res
}
```

```{r context = "server", echo = FALSE}
# whether to run in shiny-reactive or mock-reactive mode
use_shiny <- TRUE

# don't change this block
if (! use_shiny) {
  reactive <- react_calc # comment this out for shiny mode
  reactiveVal <- reactive_value_holder
  req <- isolate <- I

  output <- list()
  renderPlot <- renderText <- renderTable <- renderVerbatim <- I
  input <- list(response = "High BP",
                explan_var = "Age", show_ci = TRUE, hold_trials = TRUE, samp_mode = "sample",
                samp_n = "100", seed = "1", smooth = 1, logistic = TRUE)
}
# below this are the reactive functions and state.

# The state
current_sample      <- NULL
# current_mod_vals    <- NULL
trial_sample        <- NULL
trial_mod_vals      <- NULL
ntrials             <- 0L
prev_trial_samps    <- NULL
prev_trial_mod_vals <- NULL

get_data_frame  <- reactive({
  NHANES %>% mutate(none = "All Cases")
})
get_full_data <- reactive({
  req(input$response)

    # create the binary response
  if (input$response == "High BP") {
    level_names <- c("high", "not high")
    binary <- get_data_frame()[["BPSys1"]] > 130
  } else if (input$response == "Above Poverty Level") {
    level_names <- c("above", "below")
    binary <- get_data_frame()[["Poverty"]] > 1
  } else if (input$response == "Own Home") {
    level_names = c("Own", "Don't")
    binary <- get_data_frame()[["HomeOwn"]] == "Own"
  } else if (input$response == "Pregnant") {
    level_names <- c("pregnant", "not")
    binary <- get_data_frame()[["Pregnant"]] == "Yes"
    
  } else if (input$response == "Depressed") {
    level_names <- c("mid-high", "not")
    binary <- get_data_frame()[["Depressed"]] != "None"
  } else {
    stop("Unknown response variable: fix this in code.")
  }
  
  binary <- as.numeric(binary)
  coded <- level_names[2 - binary]
  res <- get_data_frame()[input$explan] 
  names(res) <- "explan"
  nquantiles <- as.numeric(input$quantiles)
  if (nquantiles > 0 && is.numeric(res$explan)) 
    res$explan <- mosaic::ntiles(res$explan, n = nquantiles, format = "rank")
    
  
  res[["coded"]] <- coded
  res[["binary"]] <- binary
  
  res %>% na.omit()
})
samp_size <- reactive({
  as.numeric(input$samp_n)
})

observe({
  input$explan
  input$response
  input$samp_n

  clean_the_state()
})
  
observe({
  input$hold_trials
  if (ntrials > 0 && !input$hold_trials) clean_the_state()
})

observe({
  input$samp_n
  updateCheckboxInput(session, "hold_trials", value = FALSE)
})


get_base_sample <- reactive({
  input$explan
  input$response
  input$seed
  input$samp_n
  input$quantiles
  
  if (is.null(current_sample) | !(isolate(input$hold_trials))) {
    set.seed(as.integer(Sys.time()))
    res <- get_full_data() %>% sample_n(size = samp_size()) 
    res$none <- "All Cases" # when there is no explanatory varible.
    current_sample <<- res
    clean_the_state()
  } else {
    res <- current_sample
  }
  
  res
})

current_mod_vals <- reactive({
  input$explan
  input$response
  input$samp_n
  
  get_model_vals(data = get_base_sample(),
                 logistic = input$logistic,
                 form = model_formula())
})

n_explan_levels <- reactive({
  length(unique(get_full_data()[[input$explan]]))
})

clean_the_state <- reactive({
  input$hold_trials 
  
  ntrials <<- 0L
  # make the simulations empty
  trial_sample        <<- NULL
  trial_mod_vals      <<- NULL
  prev_trial_samples  <<- NULL
  prev_trial_mod_vals <<- NULL
  FALSE
})


# input$hold is a flag saying whether to get a base sample or a simulated sample
update_trials <- reactive({
  # req(input$hold_trials)
  input$smooth
  input$logistic
  input$seed
  input$response
  input$explan
  input$samp_n
  input$samp_mode
  
  if (! isolate(req(input$hold_trials))) {
    clean_the_state()
    return(FALSE)
  } else {
    ntrials <<- ntrials + 1L
    if (input$samp_mode == "resample") {
      res <- get_base_sample() %>% sample_n(size = samp_size(), replace = TRUE)
    } else {
      res <- get_a_sample()
    }

    res <- res %>% 
      mutate(trial_number = ntrials, 
             inf_color = ifelse(input$samp_mode == "sample", 
                                LA_color("sample_trial"), 
                                LA_color("resample_trial")))
    
    trial_sample <<- res # store new value
    new_mod_vals <- 
      get_model_vals(data = res, logistic = input$logistic, form = model_formula()) %>%
      mutate(trial_number = ntrials, 
             inf_color    = ifelse(input$samp_mode == "sample", 
                                   LA_color("sample_trial"), 
                                   LA_color("resample_trial")))
    trial_mod_vals <<- new_mod_vals
    prev_trial_samps <<- bind_rows(prev_trial_samps, trial_sample)
    prev_trial_mod_vals <<- bind_rows(prev_trial_mod_vals, trial_mod_vals)
  
    return(TRUE)
  }
})


get_seed <- reactive({
  input$seed
  return(as.integer(Sys.time()))
})

get_a_sample <- reactive({
  input$seed
  input$response
  input$explan
  input$samp_n
  
  set.seed(get_seed())
  
  get_full_data() %>% sample_n(size = samp_size())
})

plot_formula <- reactive({
  binary ~ explan
})
model_formula <- reactive({ 
  if (input$explan == "none") {
    binary ~ 1
  } else if (quantitative_explan_var()) {
    as.formula(paste("binary ~ ns(explan,", input$smooth, ")"))
  } else {
    binary ~ explan
  } 
})

quantitative_explan_var <- reactive({
  input$explan
  input$quantiles
  if (input$quantiles != 0) return(FALSE)
  
  is.numeric(get_full_data()[["explan"]])
})

outcome_labels <- reactive({
  unique(get_full_data()[c("coded", "binary")]) %>% arrange(binary)
})

graphics <- reactive({
  input$explan
  input$response
  input$hold_trials
  get_a_sample()
  get_base_sample()
  
  jitter_width <- ifelse(quantitative_explan_var(), 0, 0.1)
  level_labs <- outcome_labels()$coded
  second_axis = dup_axis(name = "Numeric", 
                         breaks = seq(0, 1, by = 0.2), 
                         labels = c(0, "0.2", "0.4", "0.6", "0.8", 1))
  P <- gf_jitter(plot_formula(), data = get_base_sample(), height = 0.05, 
                 width = jitter_width, alpha = 0.5, color = LA_color("sample", "no covar")) %>%
       gf_labs(y = input$response, x = input$explan ) 

  if (quantitative_explan_var()) {
    P <- P %>% gf_line(model_output ~ explan, 
            data = current_mod_vals(), size = 2, color = LA_color("model_fun"), alpha = 0.5)
    if (input$show_ci)
      P <- P %>% gf_errorbar(lower + upper ~ explan,
                             data = current_mod_vals(), color = LA_color("conf_int"), alpha = 0.1)
    if (ntrials > 0) {
      P <- P %>% gf_jitter(plot_formula(), data = trial_sample, height = 0.05, 
                 width = jitter_width, alpha = 0.5, 
                 color = ifelse(input$samp_mode == "sample", 
                                LA_color("sample_sim"),
                                LA_color("resample_trial"))) 

      P <- P %>% gf_line(model_output ~ explan,
                          data = prev_trial_mod_vals, color = ~ inf_color, group = ~ trial_number)
      

    }
  } else {
    # Draw error bars
    P <- P %>% gf_errorbar(model_output + model_output ~ explan,
                      data = current_mod_vals(), size = 2, 
                      color = LA_color("model_fun"), width = 0.5, alpha = 0.5)
    if (input$show_ci) {
      P <- P %>% gf_errorbar(lower + upper ~ explan, 
                             data = current_mod_vals(), size = 1, width = 0.2,
                             color = LA_color("conf_int"), alpha = 0.5)
    }
    if (ntrials > 0) {
      P <- P %>% gf_errorbar(model_output + model_output ~ explan,
                          data = prev_trial_mod_vals, 
                          width = 0.2, color = ~ inf_color, group = ~ trial_number  )

      # for categorical explanatory vars, plot the recorded trials as dots 
      # so that it's easy to see how many trials fall at each level.
        as_dots <- prev_trial_mod_vals %>% mutate(xpos = as.numeric(explan) - 0.25)
        P <- P %>% gf_jitter(model_output ~ xpos, data = as_dots, color = ~inf_color, 
                           alpha = 0.25, width = 0.05, height = 0, size = 2)

    }
  } 
    
  P %>% 
    gf_refine(scale_y_continuous(
      name = input$response, breaks = seq(0, 1, by = 0.2),
      limits = c(LOWER_GRAPH_LIMIT, UPPER_GRAPH_LIMIT), 
      labels = c(level_labs[1], "", "", "", "", level_labs[2]), sec.axis = second_axis),
      verbatim_colors()) %>% 
    gf_theme(legend.position = "none")
})
```

```{r eval = ! use_shiny, echo = FALSE}
input$seed <- sample(1:10000, 1)
input$hold_trials <- TRUE
input$samp_mode <- "sample"
for (k in 1:5) update_trials()
input$samp_mode <- "resample"
for (k in 1:5) update_trials()
graphics()
```


```{r context = "server", eval = use_shiny,  echo = FALSE}
observe({
  update_trials() # initialize the data
})
output$plot <- renderPlot({
  input$seed; 
  res <- try(graphics(), silent = TRUE)
  if (inherits(res, "try-error")) NULL
  else res
}) 
output$codebook <- renderText({
    LA_var_help("NHANES", input$response, input$explan, line_length = 40L)
})
```

<style type="text/css">
td.control {
  border:5px solid gray;
  border-radius:10px;
  padding: 5px;
  vertical-align: top;
}
td.plot {
  border:5px solid gray;
  padding: 5px;
  border-radius:10px;
  color: white;
}

</style>
