---
title: "Displaying densities"
runtime: shiny
output: html_document
---

```{r include=FALSE}
library(NHANES)
library(ggformula)
library(StatPREPshiny)
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = FALSE}
RESPONSE <- selectInput("response", "Response variable",
                 choices = c("Weight", "Height", "Poverty", "Pulse", 
                             "BMI", "TotChol", "BPSys1", "UrineVol1", 
                             "Testosterone", "Age"), 
                 width = "100px")
EXPLAN <- selectInput("explan", "Explanatory var.", choices = c("None", "Gender", "HomeOwn", "SmokeNow", "SexEver", "PregnantNow", "Depressed", "Work", "PhysActive", "AgeDecade" ), width = "100px")
C <- checkboxGroupInput("layers", "Graphics layers:",
                        c("density", "histogram", "violin"), width = "100px")
F <- radioButtons("graph_format", "Graph format", choices = c("density vs response", "response vs explanatory"))
S <- sliderInput("bw", "Smoothing:", min = 1, max = 20, value = 3, width = "150px")
P <- plotOutput("plot1", width = "500px",
                brush = brushOpts("eliminate", direction = "x", fill = NA))
```




```{r echo = FALSE, context = "server"}
the_formula <- reactive({
  basic <- paste("yval ~", input$response)
  if (input$explan != "None" ) basic <- paste(basic, "|", input$explan)
  as.formula(basic)
  })
the_formula2 <- reactive({
  basic <- paste("~", input$response)
  if (input$explan != "None" ) basic <- paste(basic, "|", input$explan)
  as.formula(basic)
})

the_data <- reactive({
  res <- NHANES
  res$yval <- 1.1 * max_y_value() 
  res$None <- "All together"
  res$keepers <- TRUE

  res[c(input$response, input$explan, "yval", "keepers")] %>% na.omit()
})

observe({
  req(input$response)
  M <- diff(range(the_data()[[input$response]], na.rm = TRUE))
  M <- 10^floor(log10(M))
  
  updateSliderInput(session, "bw", max = M/5, min = M/250, value = M/20, step = M/250)
})

max_y_value <- reactive(switch(input$response, 
                             "Weight" = 0.018,
                             "Height" = 0.031,
                             "Testosterone" = 0.01,
                             "TotChol" = 0.12,
                             "Pulse"   = 0.35,
                             "BPSys1"  = 0.03,
                             "UrineVol1" = 0.01,
                             "BMI"     = 0.055,
                             "Age"     = 0.015,
                             "Poverty" = 0.5))
                      
max_x_value <- reactive(max(NHANES[[input$response]], na.rm = TRUE))

bw <- reactive(as.numeric(input$bw))

violin_graphics <- reactive({
  set.seed(101)
  all_data <- the_data()
  keepers <- all_data[all_data$keepers,]
  this_formula <- as.formula(paste(input$response, "~", input$explan))
  A <- gf_jitter(this_formula, data = keepers, alpha = 0.05,
                 width = 0.1, height = 0, size = bw()/10) %>%
    gf_violin(this_formula, data = keepers, bw = bw(), fill = "green", alpha = 0.2, color = NA)

  A
})

graphics <- reactive({
    set.seed(101) # so the dots don't move around
    all_data <- the_data()
    keepers <- all_data[all_data$keepers,]
    A <- gf_jitter(the_formula(), data = keepers, alpha = 0.05, 
                   height = 0.1 * max_y_value(),
                   size = bw() / 10)
    if ("density" %in% input$layers)
      A <- A %>% gf_density(the_formula2(), data = keepers, alpha = 0.5, 
                            color = "blue", fill = "blue",
                            bw = bw())
    if ("histogram" %in% input$layers)
      A <- A %>% gf_dhistogram(the_formula2(), 
                               data = keepers, 
                               alpha = 0.7, color = "black", fill = NA,
                               binwidth = bw() / 0.5)
    if ("violin" %in% input$layers) {
      if (input$explan == "None") {
      ribbon_coords <- ribbon_for_violin(keepers[[input$response]], 
                                         vpos = 1.1 * max_y_value(), 
                                         vwidth = 0.2 * max_y_value(),
                                         bw = bw())
      } else {
        ribbon_coords <- ribbon_for_violin(keepers[[input$response]], 
                                         keepers[[input$explan]],
                                         vpos = 1.1 * max_y_value(),
                                         vwidth = 0.2 * max_y_value(),
                                         bw = bw())
        ribbon_coords[[input$explan]] <- ribbon_coords$group
      }
      # For unknown reason, gf_ribbon() doesn't work. So mimic it.
      A <- A %>% gf_segment(top + bottom ~ x + x, data = ribbon_coords, 
                             alpha = 0.2, color = "green")
    }
    return(A %>% 
             gf_lims(y = c(0, 1.2*max_y_value()*
                               ifelse(length(input$layers)==0, 1, NA)), 
                     x = c(-.1,1) * max_x_value()) %>% 
             gf_labs(y = ifelse(length(input$layers)==0, "", "Density")))
  })

output$plot1 <- renderPlot({
  if (input$graph_format == "density vs response") graphics()
  else violin_graphics()})
```

<table><tr><td class="control">`r RESPONSE` `r EXPLAN` `r C` `r S` `r F`</td><td class="plot">`r P`</td></tr></table>



<style type="text/css">
td.control {
  border:1px solid gray;
  border-radius:10px;
  padding: 5px;
  vertical-align: top;
}
td.plot {
  border:1px solid gray;
  padding: 5px;
  border-radius:10px;
  color: white;
}

</style>


