---
title: 'Little App Guide: Smoothing'
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
library(LittleApps)
library(dplyr)
library(forcats)
library(NHANES)
library(mosaic)
knitr::opts_chunk$set(echo = FALSE, out.width = "80%", fig.align = "center")
# Dicotomize some variables of particular interest
NHANES <- NHANES %>%
  mutate(PregnantNow = fct_recode(PregnantNow, NULL = "Unknown"),
         HomeOwn     = fct_recode(HomeOwn,    NULL = "Other" ),
         Depressed   = fct_recode(Depressed,   Several = "Most"),
         Work        = fct_recode(Work, NotWorking = "Looking"),
         LittleInterest = fct_recode(LittleInterest, Several = "Most"))
get_data <- function(V) {
  res <- if (length(V$covar) == 0 || any(V$covar == "None selected")) {
    NHANES[ , c(V$explan, V$response)]
  } else {
    NHANES[ , c(V$explan, V$response, V$covar)] %>%
      na.omit() %>%
      sample_n(size = V$samp_n)
  }
  
  res %>% sample_n(size = V$samp_n)
}

```

This Little App 

```{r warning = FALSE}
V <- list()
V$samp_n <- 200
V$response <- "Height"
V$explan <- "Age"
 V$covar <- "Gender"
 V$model_formula <- Height ~ Age * Gender
# V$covar <- "None selected"
# V$model_formula <- Height ~ Age
set.seed(101)
V$data <- get_data(V)
V$sd <- TRUE
V$y_range <- range(NHANES[ , V$response], na.rm = TRUE)
V$show_mod_vals <- FALSE
V$trace_horiz <- FALSE
V$trace_vert <- FALSE

smoother_plot(V)
```

